kind: PersistentVolume
apiVersion: v1
metadata:
  name: sonarqube-postgresql-pv
  namespace: sonarqube
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/glusterfs/sonarqube-postgresql
    
