kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarqube-postgresql-pvc
  namespace: sonarqube
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
      
